## Numpy : 

NumPy is a Python library. NumPy is used for working with arrays.
NumPy is short for "Numerical Python". It is the fundamental package for scientific computing with Python.


## Numpy Array : 

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.



In [1]:
## Importing Numpy

import numpy as np  

In [3]:
my_lst=[[1,2,3,4,5] , [5,4,3,2,1]]
# creating array object
arr = np.array(my_lst)

In [4]:
# Printing type of arr object 
print("Array is of type: ", type(arr)) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 5)
Size of array:  10
Array stores elements of type:  int32


In [6]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


## Indexing of Array

In [8]:
# Initialzing Array

arr = np.array([[1,2,3,4,5] ,[6,7,8,9,0] , [5,6,7,4,3]])
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [5 6 7 4 3]]


In [11]:
# Slicing of Array

sliced_arr = arr[:1,:3]
sliced_arr

array([[1, 2, 3]])

In [12]:
arr[0:2,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [8]:
arr2 = [2,4,7,5,9]
arr3 = [3,5,8,6,1]

arra = np.array(arr2)
arrb = np.array(arr3)

print(arr2+arr3)
print(arra+arrb)
print(arra*arrb)

[2, 4, 7, 5, 9, 3, 5, 8, 6, 1]
[ 5  9 15 11 10]
[ 6 20 56 30  9]


### numpy.arange(): $ This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

In [2]:
# numpy.arange([start, stop, step])
import numpy as np
arr=np.arange(1, 20, 2)
print(arr)

arr1=np.arange(50, 20, -2, dtype=np.float32)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]
[50. 48. 46. 44. 42. 40. 38. 36. 34. 32. 30. 28. 26. 24. 22.]


###  numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits.

In [27]:
np.linspace(2,60,3 ,dtype=np.int32)

np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### numpy.empty(): This function create a new array of given shape and type, without initializing value.

In [6]:
arr2 = np.empty([5,5], dtype = np.int32, order = 'f')
print(arr2)

np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

[[     50      48      84      56      51]
 [     48      49      49      58      52]
 [     50      45      50      50      54]
 [     52      48      58      51      90]
 [     45      51      50      46 6619243]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### numpy.zeros(): This function is used to get a new array of given shape and type, filled with zeros(0).

### numpy.ones(): This function is used to get a new array of given shape and type, filled with ones(1).

In [12]:
arr1 = np.zeros([4, 3],
        dtype = np.int32,
        order = 'f')

arr2 = np.ones([4, 3],
        dtype = np.int32,
        order = 'f')
print(arr1)
print(arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


### Copy and view
#### The main difference between copy and view is that the copy is the new array whereas the view is the view of the original array. In other words, it can be said that the copy is physically stored at another location and view has the same memory location as the original array.



In [9]:
# Copy: This is also known as Deep Copy.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(x)
print(arr)

# View: This is also known as Shallow Copy.

arr4 = np.array ([1,4,6,9,3,5,8])
v = arr4.view()
print(id(arr4))
print(id(v))
arr4[3]= 19
print(arr4)
print(v)


[1 2 3 4 5]
[42  2  3  4  5]
2007793843536
2007816211312
[ 1  4  6 19  3  5  8]
[ 1  4  6 19  3  5  8]


In [19]:
###Some condition very useful for creating exploratory Data Analysis

val = 5
arr5 =np.array([2,5,7,8,9,4,1])

print(arr5<val)

## Exact digit which is less than val
print(arr5[arr5<5])

print(arr5*5)
print(arr5/val)

[ True False False False False  True  True]
[2 4 1]
[10 25 35 40 45 20  5]
[0.4 1.  1.4 1.6 1.8 0.8 0.2]


### numpy.random.rand() Function Syntax
The numpy.random.rand() function creates an array of specified shapes fills it with random values uniformly distributed between 0 and 1.It is commonly used for creating random arrays in various applications such as simulations and machine learning. 

Syntax : numpy.random.rand(d0, d1, …, dn)

In [9]:
import numpy as np
array = np.random.rand(3,3)
print ("2D Array :\n", array)

2D Array :
 [[0.53415792 0.39164211 0.45859427]
 [0.04185158 0.65218899 0.43401314]
 [0.06002889 0.37712081 0.33712614]]


In [9]:
import numpy as np

np.random.seed(42)  # Set the seed for reproducibility
random_array = np.random.rand(2, 3)  # Generates the same 2x3 array of random numbers each time you run the code.
print(random_array)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


### numpy.random.randn:

This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
Syntax: numpy.random.randn(d0, d1, ..., dn)
Parameters: d0, d1, ..., dn are the dimensions of the output array. If no argument is provided, a single random value is generated.

In [10]:
arr5 = np.random.randn(4,6)
print(arr5)

[[ 1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877 -0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375]]


# Integers
The randint() method takes a size parameter where you can specify the shape of an array.

In [6]:
from numpy import random

x=random.randint(100, size=(5))

print(x,'\n')

x = random.randint(100, size=(3, 5))

print(x)

[24 43 70 63 66] 

[[96 79 11 81 98]
 [ 7 85 23 80 22]
 [19 90 78 36  2]]


In [12]:
## The choice() method takes an array as a parameter and randomly returns one of the values.

from numpy import random

x = random.choice ([2,6,9,3,5,7])
print(x)

##Add a size parameter to specify the shape of the array.

x= random.choice([1,4,7,9,2,6,8,3,5], size=(4,3))

print(x)

7
[[8 6 4]
 [9 7 2]
 [7 2 5]
 [4 8 2]]


In [14]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.shape)

(5,)
